-- Maintenance expenses table to record costs related to maintenance requests
create table if not exists maintenance_expenses (
  expense_id bigint generated by default as identity primary key,
  request_id bigint not null references maintenance_requests(request_id) on delete cascade,
  amount numeric(10,2) not null check (amount >= 0),
  description text,
  vendor text,
  paid_at timestamptz,
  created_by bigint references users(user_id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Helpful index for monthly summaries
create index if not exists idx_maintenance_expenses_created_at on maintenance_expenses(created_at);
create index if not exists idx_maintenance_expenses_request_id on maintenance_expenses(request_id);
